// <auto-generated />
using System;
using CMD.Appointment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMD.Appointment.Data.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20240918134740_Reset2.0")]
    partial class Reset20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMD.Appointment.Domain.Entities.AppointmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfVisit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3968),
                            Date = new DateOnly(2024, 9, 20),
                            DoctorId = 1,
                            Email = "john.doe@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3969),
                            Message = "Please bring your medical reports.",
                            PatientId = 1,
                            Phone = "919876543210",
                            PurposeOfVisit = "Consultation",
                            Status = 0,
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3974),
                            Date = new DateOnly(2024, 9, 22),
                            DoctorId = 2,
                            Email = "jane.smith@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3975),
                            Message = "Appointment canceled by patient.",
                            PatientId = 2,
                            Phone = "919234567890",
                            PurposeOfVisit = "Follow Up",
                            Status = 1,
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3978),
                            Date = new DateOnly(2024, 9, 25),
                            DoctorId = 3,
                            Email = "alice.jones@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3979),
                            Message = "Dental checkup completed.",
                            PatientId = 3,
                            Phone = "919345678901",
                            PurposeOfVisit = "Treatment",
                            Status = 2,
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3981),
                            Date = new DateOnly(2024, 9, 26),
                            DoctorId = 4,
                            Email = "mike.brown@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3982),
                            Message = "Immediate attention required.",
                            PatientId = 4,
                            Phone = "919456789012",
                            PurposeOfVisit = "Emergency",
                            Status = 0,
                            Time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3985),
                            Date = new DateOnly(2024, 9, 28),
                            DoctorId = 5,
                            Email = "chris.evans@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3985),
                            Message = "Doctor is unavailable, appointment rescheduled.",
                            PatientId = 5,
                            Phone = "919567890123",
                            PurposeOfVisit = "General Checkup",
                            Status = 1,
                            Time = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3988),
                            Date = new DateOnly(2024, 9, 30),
                            DoctorId = 2,
                            Email = "emma.williams@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3989),
                            Message = "Please bring your test reports.",
                            PatientId = 1,
                            Phone = "919678901234",
                            PurposeOfVisit = "Typhoid",
                            Status = 0,
                            Time = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3991),
                            Date = new DateOnly(2024, 10, 1),
                            DoctorId = 3,
                            Email = "olivia.johnson@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3992),
                            Message = "Bring blood test results.",
                            PatientId = 2,
                            Phone = "919789012345",
                            PurposeOfVisit = "Malaria",
                            Status = 0,
                            Time = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3995),
                            Date = new DateOnly(2024, 10, 3),
                            DoctorId = 4,
                            Email = "ava.miller@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3995),
                            Message = "Patient requested cancellation.",
                            PatientId = 3,
                            Phone = "919890123456",
                            PurposeOfVisit = "Cold",
                            Status = 1,
                            Time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3998),
                            Date = new DateOnly(2024, 10, 5),
                            DoctorId = 5,
                            Email = "isabella.taylor@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(3999),
                            Message = "Take medication before visit.",
                            PatientId = 4,
                            Phone = "919901234567",
                            PurposeOfVisit = "Fever",
                            Status = 0,
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4002),
                            Date = new DateOnly(2024, 10, 7),
                            DoctorId = 1,
                            Email = "mia.anderson@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4002),
                            Message = "No special instructions.",
                            PatientId = 5,
                            Phone = "919012345678",
                            PurposeOfVisit = "Consultation",
                            Status = 0,
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4005),
                            Date = new DateOnly(2024, 10, 10),
                            DoctorId = 3,
                            Email = "lucas.martin@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4005),
                            Message = "Doctor unavailable, please reschedule.",
                            PatientId = 1,
                            Phone = "919123456789",
                            PurposeOfVisit = "Follow Up",
                            Status = 1,
                            Time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4008),
                            Date = new DateOnly(2024, 10, 12),
                            DoctorId = 4,
                            Email = "sophia.lee@example.com",
                            LastModifiedBy = "Admin",
                            LastModifiedDate = new DateTime(2024, 9, 18, 19, 17, 40, 74, DateTimeKind.Local).AddTicks(4009),
                            Message = "Please bring your previous reports.",
                            PatientId = 2,
                            Phone = "919234567890",
                            PurposeOfVisit = "Treatment",
                            Status = 0,
                            Time = new TimeOnly(16, 30, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
